language:
  - nix

script:
  - nix-shell --pure --command 'cd src; make'

deploy:
  - provider: s3
    bucket: milewski-ctfp-pdf-kr
    access_key_id: '$ARTIFACTS_KEY'
    secret_access_key: '$ARTIFACTS_SECRET'
    region: ap-northeast-2
    acl: public_read
    local_dir: out
    skip_cleanup: true
    on:
      all_branches: true
      repo: jwvg0425/milewski-ctfp-pdf-kr
